load("@com_github_iljakroonen_rules_kotlin//:kotlin.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "logging",
    srcs = glob([
        "*.kt",
    ]),
    visibility = [
        "//visibility:public",
    ],
)
